cask "intellij-idea"
cask "istat-menus"
cask "sublime-text"
cask "slack"
cask "docker"
cask "iterm2"
cask "google-chrome"
cask "postman"

# Go
brew install go

# Web
brew "hugo"

# JavaScript
brew "npm"
